---
  server:
    port: 8080

  spring:
    datasource:
      url: jdbc:postgresql://192.168.0.120:5432/task_tracker
      username: postgres
      password: mysecretpassword
      driver-class-name: org.postgresql.Driver
    jpa:
      hibernate:
        ddl-auto: update